# Generated by Django 5.0.3 on 2024-03-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_embed_alter_category_name_alter_video_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embed',
            old_name='name',
            new_name='embed_code',
        ),
    ]
